# Generated by Django 3.1.1 on 2021-04-06 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Название')),
                ('content', models.CharField(max_length=1000, verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(blank=True, choices=[('active', 'активно'), ('not_active', 'не активно')], default='active', max_length=100, verbose_name='Статус')),
                ('activity', models.BooleanField(blank=True, default=False, verbose_name='Разрешение на публикацию')),
                ('tag', models.CharField(blank=True, default='', max_length=50, verbose_name='Тег')),
                ('many_news', models.FileField(blank=True, upload_to='files/file_news/', verbose_name='Файл новостей')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_news', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'permissions': (('create_and_edit', 'Может создавать и редактировать'), ('approved', 'Одобрено модератором')),
            },
        ),
        migrations.CreateModel(
            name='ImagesNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='files/images/', verbose_name='Изображение')),
                ('news', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_news', to='app_news.news', verbose_name='Новость')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=50)),
                ('text', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('news', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_news.news', verbose_name='Новость')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
