# Generated by Django 3.2.3 on 2021-06-04 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Name')),
                ('content', models.CharField(max_length=1000, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('not_active', 'not_active')], default='active', max_length=100, verbose_name='Status')),
                ('activity', models.BooleanField(blank=True, default=False, verbose_name='Permission to publish')),
                ('tag', models.CharField(blank=True, default='', max_length=50, verbose_name='Tag')),
                ('many_news', models.FileField(blank=True, upload_to='files/file_news/', verbose_name='File many news')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_news', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'permissions': (('create_and_edit', 'create and edit'), ('approved', 'approved moderator')),
            },
        ),
        migrations.CreateModel(
            name='ImagesNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='files/images/', verbose_name='Images')),
                ('news', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_news', to='rest.news', verbose_name='News')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=50)),
                ('text', models.CharField(max_length=500, verbose_name='Comment')),
                ('news', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rest.news', verbose_name='News')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
